### ISSUE TITLE
Refactor the SessionsController

### ISSUE THREAD

**Issue by achasveachas** [CodeToJoyForever/BeInTheKnow_backend#23]
Some refactoring suggestions for the `SessionsController`:

- The indentation for the `create` method can really use some love. Having proper indentation is not just a way for disgruntled instructors/reviewers to dock you points, it can make a huge difference to the readability of the code /9especially for large files).

- [Line 10](https://github.com/CodeToJoyForever/BeInTheKnow_backend/blob/36989924340bfbac1a1f9997a05a901ee9064620/app/controllers/api/sessions_controller.rb#L10): One of my favorite Ruby features is the Safe Navigation operator. You can read about it here. Consider refactoring this line using safe navigation.

- If the `destroy` method isn't needed delete it. Ideally, commented out code should stay out of master.

**Comment by AAM77** [comment]
Issues have been addressed. Thank you for your corrections & suggestions! :)
