### ISSUE TITLE
Refacor the UsersController

### ISSUE THREAD

**Issue by achasveachas** [CodeToJoyForever/BeInTheKnow_backend#24]
- There are lots of empty lines that can be removed.
- [Line 16](https://github.com/CodeToJoyForever/BeInTheKnow_backend/blob/36989924340bfbac1a1f9997a05a901ee9064620/app/controllers/api/users_controller.rb#L13): We aren't taking the `username`...
- We have `user_params` but aren't using them, if we pass `user_params` to `User.create` that would take care of last issue as well.
- [Line 18](https://github.com/CodeToJoyForever/BeInTheKnow_backend/blob/36989924340bfbac1a1f9997a05a901ee9064620/app/controllers/api/users_controller.rb#L18): Either put the whole json on one line or put the closing bracket on the next line.
- `destroy` method: we use `@user` but never defined it, if we would try to call this method we would get an `UndefinedMethodError` for nil class (having tests would have caught this). 
- [Line 32](https://github.com/CodeToJoyForever/BeInTheKnow_backend/blob/36989924340bfbac1a1f9997a05a901ee9064620/app/controllers/api/users_controller.rb#L32): Add a space after `:email`

**Comment by AAM77** [comment]
Issues have been addressed. Thank you for your corrections & suggestions! :)
